import { test } from 'node:test';
import assert from 'node:assert/strict';
import { products } from '../catalog.mjs';
import { createPlatform,platformRequest,demoOperators } from '../dist/platform-core.js';
const now='2026-09-14T12:00:00.000Z';
const admin={operator:demoOperators[0]},dealer={operator:demoOperators[2]},salon={operator:demoOperators[1]};
const member={id:'buyer-a',name:'デモ 花子',kana:'デモ ハナコ',email:'a@example.test'},actor={member};
const customer={name:'デモ 花子',postal:'0000000',prefecture:'東京都',city:'架空市',street:'1-2-3',phone:'0300000000'};
function fixture(){const state=createPlatform(products,now);state.orders=[];state.purchaseOrders=[];state.profiles=[];state.events=[];state.products.forEach(p=>p.stock=products.find(x=>x.id===p.id).stock);platformRequest(state,'/profile','PATCH',{salonId:'lumiere'},actor,now);platformRequest(state,`/admin/members/${actor.member.id}/staff`,'PATCH',{staffId:'haruka'},{operator:demoOperators[0]},now);return state;}
function request(state,items=[{id:'shampoo-moist',quantity:2,price:2860},{id:'oil-smooth',quantity:1,price:2640}]){return {requestKey:crypto.randomUUID(),salonId:'lumiere',items,customer};}
test('sample workspace seeds real linked orders and valid stock',()=>{const s=createPlatform(products,now);assert.equal(s.orders.length,8);assert.equal(s.purchaseOrders.length,8);assert.ok(s.products.every(p=>p.stock>=0));assert.ok(s.orders.every(o=>s.purchaseOrders.some(p=>p.orderId===o.id)));});
test('a member order creates one BICMA shipment once, reserves stock, and freezes prices and staff',()=>{const s=fixture(),input=request(s),before=s.products[0].stock;const o=platformRequest(s,'/orders','POST',input,actor,now);assert.equal(o.total,9020);assert.equal(o.items[0].cost,undefined);assert.equal(s.purchaseOrders.length,1);assert.equal(s.products[0].stock,before-2);assert.equal(platformRequest(s,'/orders','POST',input,actor,now).id,o.id);assert.equal(s.purchaseOrders.length,1);assert.equal(s.products[0].stock,before-2);assert.throws(()=>platformRequest(s,'/orders','POST',{...input,customer:{...customer,name:'changed'}},actor),/内容を変更/);platformRequest(s,'/admin/products/shampoo-moist','PATCH',{stock:10,price:3000,cost:1700,enabled:true},admin);platformRequest(s,'/admin/members/buyer-a','PATCH',{salonId:'atelier',staffId:'mio'},admin);const stored=platformRequest(s,'/orders','GET',undefined,actor)[0];assert.equal(stored.items[0].price,2860);assert.equal(stored.staffName,'HARUKA');assert.equal(stored.salonId,'lumiere');});
test('shipment transitions drive tracking, delivery and full return refund',()=>{const s=fixture(),o=platformRequest(s,'/orders','POST',request(s),actor,now),pos=s.purchaseOrders.filter(p=>p.orderId===o.id);const update=(p,status)=>platformRequest(s,'/admin/purchase-orders/'+p.id,'PATCH',{status,carrier:'デモ配送',tracking:'DEMO-123456'},dealer);assert.equal(pos.length,1);assert.throws(()=>update(pos[0],'shipped'),/順に/);update(pos[0],'accepted');update(pos[0],'shipped');assert.equal(s.orders[0].status,'shipped');assert.throws(()=>platformRequest(s,'/orders/'+o.id+'/cancel','POST',{},actor),/出荷後/);for(const p of pos)update(p,'delivered');assert.equal(s.orders[0].status,'delivered');const seen=platformRequest(s,'/orders','GET',undefined,actor)[0];assert.ok(seen.shipments.every(p=>p.tracking==='DEMO-123456'));platformRequest(s,'/orders/'+o.id+'/return','POST',{reason:'デモ：返品テスト'},actor);assert.throws(()=>platformRequest(s,'/admin/orders/'+o.id+'/refund','POST',{},dealer),/権限/);platformRequest(s,'/admin/orders/'+o.id+'/refund','POST',{},admin);const stock=s.products[0].stock;platformRequest(s,'/admin/orders/'+o.id+'/refund','POST',{},admin);assert.equal(s.products[0].stock,stock);assert.equal(stock,24);const settlement=platformRequest(s,'/admin/snapshot','GET',undefined,admin).settlements[0];assert.equal(settlement.refunded,9020);assert.equal(settlement.proceeds,0);});
test('cancellation restores all suppliers once, removes payable balances and blocks shipment',()=>{const s=fixture(),o=platformRequest(s,'/orders','POST',request(s),actor);platformRequest(s,'/orders/'+o.id+'/cancel','POST',{},actor);platformRequest(s,'/orders/'+o.id+'/cancel','POST',{},actor);assert.equal(s.products[0].stock,24);assert.equal(s.products[2].stock,30);assert.ok(s.purchaseOrders.every(p=>p.status==='cancelled'));assert.throws(()=>platformRequest(s,'/admin/purchase-orders/'+s.purchaseOrders[0].id,'PATCH',{status:'accepted'},dealer),/変更できません/);assert.equal(platformRequest(s,'/admin/snapshot','GET',undefined,admin).settlements[0].fee,0);});
test('authorization isolates member, salon and dealer data, and rejects forged access',()=>{const s=fixture(),input=request(s),o=platformRequest(s,'/orders','POST',input,actor);const other={member:{id:'buyer-b',name:'デモ 別会員',kana:'デモ カイイン',email:'b@example.test'}};assert.throws(()=>platformRequest(s,'/orders','POST',request(s),{}),/ログイン/);assert.deepEqual(platformRequest(s,'/orders','GET',undefined,other),[]);assert.throws(()=>platformRequest(s,'/orders/'+o.id+'/cancel','POST',{},other),/操作できません/);assert.throws(()=>platformRequest(s,'/orders','POST',input,other),/取得できません/);assert.throws(()=>platformRequest(s,'/admin/snapshot','GET',undefined,{}),/ログイン/);const d=platformRequest(s,'/admin/snapshot','GET',undefined,dealer);assert.equal(d.orders.length,0);assert.equal(d.profiles.length,0);assert.equal(d.purchaseOrders.length,1);assert.ok(d.products.every(p=>p.dealerId==='bicma'));assert.throws(()=>platformRequest(s,'/admin/purchase-orders/'+s.purchaseOrders[0].id,'PATCH',{status:'accepted'},{operator:{role:'dealer',dealerId:'other',name:'x'}}),/他社/);assert.throws(()=>platformRequest(s,'/admin/products/shampoo-moist','PATCH',{stock:5,price:1},dealer),/在庫数のみ/);assert.throws(()=>platformRequest(s,'/admin/products/shampoo-moist','PATCH',{stock:5,price:1,cost:1,enabled:true},salon),/権限/);const differentSalon={operator:{role:'salon',salonId:'atelier'}};assert.equal(platformRequest(s,'/admin/snapshot','GET',undefined,differentSalon).orders.length,0);});
test('invalid quantity, stale price, insufficient stock and paused salon cannot create orders',()=>{const s=fixture();for(const quantity of [0,-1,1.5,100,'1'])assert.throws(()=>platformRequest(s,'/orders','POST',request(s,[{id:'shampoo-moist',quantity,price:2860}]),actor));assert.throws(()=>platformRequest(s,'/orders','POST',request(s,[{id:'shampoo-moist',quantity:1,price:1}]),actor),/価格/);assert.throws(()=>platformRequest(s,'/orders','POST',request(s,[{id:'shampoo-moist',quantity:25,price:2860}]),actor),/在庫/);assert.equal(s.orders.length,0);assert.equal(s.products[0].stock,24);platformRequest(s,'/admin/salons/lumiere','PATCH',{name:'LUMIÈRE',owner:'架空店',feeRate:7,enabled:false},admin);assert.throws(()=>platformRequest(s,'/orders','POST',request(s),actor),/停止/);assert.equal(s.orders.length,0);});
test('shipping boundary and settlement totals remain consistent after fee changes',()=>{const s=fixture();const q=platformRequest(s,'/quote','POST',request(s,[{id:'shampoo-moist',quantity:4,price:2860}]),actor);assert.equal(q.shipping,0);const o=platformRequest(s,'/orders','POST',request(s),actor);const report=platformRequest(s,'/admin/snapshot','GET',undefined,admin).settlements[0];assert.equal(report.proceeds,o.items.reduce((n,i)=>n+(i.price-s.products.find(p=>p.id===i.id).wholesalePrice)*i.quantity,0),'美容室の取り分は売価−卸価格');assert.equal(report.dealerNet,report.sales-report.purchase-report.proceeds-report.fee);platformRequest(s,'/admin/salons/lumiere','PATCH',{name:'変更サロン',owner:'別名',feeRate:10,enabled:true},admin);assert.equal(s.orders[0].feeRate,5);assert.equal(s.orders[0].salonName,'LUMIÈRE 表参道');assert.equal(o.seller,'F.I.Tソリューション（BICMA）','EC の販売者は F.I.Tソリューション');});
