// summary は商品一覧に出す短い説明（60字まで）、description は商品ページの説明。
// 写真は dist/assets/products/（python scripts/generate-product-photos.py で作る。ブランド・商品はすべて架空）
export const products = [
 {id:'shampoo-moist',brand:'SENA PROFESSIONAL',name:'モイストリペア シャンプー',category:'シャンプー',concerns:['ダメージヘア対策','カラーケア'],size:'500 mL',price:2860,stock:24,image:'products/shampoo-moist.webp',tag:'BEST SELLER',summary:'しっとり洗い上げ、まとまる髪へ。ダメージが気になる髪に。',description:'毎日のヘアケアに。しっとりした洗い上がりをイメージした、サロン向けのデモ商品です。',sku:'SN-SH-050'},
 {id:'treatment-repair',brand:'SENA PROFESSIONAL',name:'インテンシブ リペアマスク',category:'トリートメント',concerns:['ダメージヘア対策','パーマケア','エイジングケア'],size:'250 g',price:3520,stock:18,image:'products/treatment-repair.webp',tag:'NEW',summary:'週1回の集中ケアで、指通りのなめらかな髪に。',description:'週に一度のスペシャルケアをイメージしたヘアマスク。商品説明・容量・価格はすべて架空です。',sku:'SN-TR-025'},
 {id:'oil-smooth',brand:'SENA BOTANICAL',name:'スムース フィニッシュオイル',category:'ヘアオイル',concerns:['ダメージヘア対策','カラーケア'],size:'100 mL',price:2640,stock:30,image:'products/oil-smooth.webp',tag:'POPULAR',summary:'軽いつけ心地で、自然なつやとまとまりを。',description:'スタイリングの仕上げに使うヘアオイルをイメージしたデモ商品。自然なまとまりをテーマにしています。',sku:'SN-OL-010'},
 {id:'shampoo-air',brand:'SENA PROFESSIONAL',name:'エアリーケア シャンプー',category:'シャンプー',concerns:['ボリュームアップ','頭皮ケア'],size:'500 mL',price:2640,stock:12,image:'products/shampoo-air.webp',tag:'',summary:'ふんわり軽い洗い上がり。根元から立ち上がる髪に。',description:'軽やかな仕上がりをテーマにしたシャンプーのデモ商品です。モイストタイプとの比較もお試しいただけます。',sku:'SN-SH-051'},
 {id:'treatment-daily',brand:'SENA PROFESSIONAL',name:'デイリーケア トリートメント',category:'トリートメント',concerns:['エイジングケア','白髪対策'],size:'250 g',price:3080,stock:15,image:'products/treatment-daily.webp',tag:'',summary:'毎日使えるトリートメント。やわらかくまとまる髪へ。',description:'デイリーケアをイメージしたトリートメント。毎日のサロンワークに寄り添うデモシリーズです。',sku:'SN-TR-026'},
 {id:'oil-rich',brand:'SENA BOTANICAL',name:'リッチ モイスチャーオイル',category:'ヘアオイル',concerns:['エイジングケア','パーマケア'],size:'100 mL',price:3300,stock:0,image:'products/oil-rich.webp',tag:'',summary:'乾燥しがちな毛先を、しっとり重めに仕上げる。',description:'しっとりした質感をテーマにしたヘアオイル。売り切れ時の表示を確認するため、初期在庫は0本です。',sku:'SN-OL-011'},
 // ここから：カテゴリ・ブランドから探す画面を試すためのダミー商品（ブランド・商品・価格はすべて架空）
 {id:'sena-mask-deep',brand:'SENA PROFESSIONAL',name:'ディープリペア ヘアマスク',category:'ヘアマスク',concerns:['ダメージヘア対策','パーマケア'],size:'200 g',price:3960,stock:15,image:'products/sena-mask-deep.webp',tag:'',summary:'ハイダメージ毛に。濃密なマスクで、しっとりまとまる髪へ。',description:'ハイダメージ毛の集中ケアをイメージしたヘアマスク。週1〜2回のスペシャルケア向けのデモ商品です。',sku:'SN-MK-020',dealerId:'sena'},
 {id:'sena-milk-heat',brand:'SENA PROFESSIONAL',name:'ヒートプロテクト ヘアミルク',category:'ヘアミルク・ミスト',concerns:['ダメージヘア対策','カラーケア'],size:'120 mL',price:2420,stock:26,image:'products/sena-milk-heat.webp',tag:'',summary:'ドライヤー前のひと手間で、熱から髪を守る。',description:'ドライヤー前に使う洗い流さないトリートメントをイメージしたデモ商品です。',sku:'SN-ML-012',dealerId:'sena'},
 {id:'botanical-mist',brand:'SENA BOTANICAL',name:'ボタニカル ヘアミスト',category:'ヘアミルク・ミスト',concerns:['ダメージヘア対策'],size:'150 mL',price:2200,stock:22,image:'products/botanical-mist.webp',tag:'NEW',summary:'寝ぐせ直しに。植物のやさしい香りのヘアミスト。',description:'朝の寝ぐせ直しと、ほのかな香りをテーマにしたヘアミストのデモ商品です。',sku:'SB-MS-015',dealerId:'botanica'},
 {id:'botanical-scalp-shampoo',brand:'SENA BOTANICAL',name:'ボタニカル スカルプシャンプー',category:'シャンプー',concerns:['頭皮ケア','ボリュームアップ'],size:'400 mL',price:2970,stock:16,image:'products/botanical-scalp-shampoo.webp',tag:'',summary:'頭皮をすっきり洗う、植物由来のスカルプシャンプー。',description:'植物由来の成分をイメージした、頭皮をすっきり洗うシャンプーのデモ商品です。',sku:'SB-SH-040',dealerId:'botanica'},
 {id:'mizuha-shampoo',brand:'MIZUHA',name:'うるおい シャンプー',category:'シャンプー',concerns:['ダメージヘア対策','エイジングケア'],size:'400 mL',price:3080,stock:20,image:'products/mizuha-shampoo.webp',tag:'POPULAR',summary:'和の植物のうるおいで、しっとりやわらかな洗い上がり。',description:'和の植物をテーマにした、しっとり洗い上げるシャンプーのデモ商品です。',sku:'MZ-SH-040',dealerId:'sena'},
 {id:'mizuha-treatment',brand:'MIZUHA',name:'うるおい トリートメント',category:'トリートメント',concerns:['ダメージヘア対策','エイジングケア'],size:'400 g',price:3080,stock:19,image:'products/mizuha-treatment.webp',tag:'',summary:'髪にうるおいを与え、しなやかにまとめる。',description:'シャンプーと同じシリーズの、まとまりを出すトリートメントのデモ商品です。',sku:'MZ-TR-040',dealerId:'sena'},
 {id:'mizuha-camellia-oil',brand:'MIZUHA',name:'椿 ヘアオイル',category:'ヘアオイル',concerns:['ダメージヘア対策','白髪対策'],size:'80 mL',price:3300,stock:9,image:'products/mizuha-camellia-oil.webp',tag:'BEST SELLER',summary:'椿のオイルで、毛先までつややかに。',description:'椿をテーマにした、毛先までつややかに仕上げるヘアオイルのデモ商品です。',sku:'MZ-OL-008',dealerId:'botanica'},
 {id:'mizuha-mask',brand:'MIZUHA',name:'濃密 ヘアマスク',category:'ヘアマスク',concerns:['エイジングケア','パーマケア'],size:'180 g',price:4180,stock:11,image:'products/mizuha-mask.webp',tag:'',summary:'ハリ・コシが気になる髪に。濃密なヘアマスク。',description:'年齢とともに気になる髪のハリ・コシをテーマにしたヘアマスクのデモ商品です。',sku:'MZ-MK-018',dealerId:'sena'},
 {id:'calme-scalp-shampoo',brand:'CALMÉ SCALP',name:'スカルプクレンジング シャンプー',category:'シャンプー',concerns:['頭皮ケア','ボリュームアップ'],size:'300 mL',price:3520,stock:17,image:'products/calme-scalp-shampoo.webp',tag:'',summary:'皮脂やにおいをすっきり。頭皮から整えるシャンプー。',description:'頭皮の皮脂やにおいをすっきり洗うことをテーマにしたシャンプーのデモ商品です。',sku:'CS-SH-030',dealerId:'botanica'},
 {id:'calme-scalp-serum',brand:'CALMÉ SCALP',name:'スカルプセラム',category:'スカルプケア',concerns:['頭皮ケア','エイジングケア'],size:'60 mL',price:4950,stock:13,image:'products/calme-scalp-serum.webp',tag:'NEW',summary:'お風呂上がりの頭皮に。すっとなじむ頭皮用美容液。',description:'お風呂上がりの頭皮に使う美容液をイメージしたデモ商品です。',sku:'CS-SR-006',dealerId:'botanica'},
 {id:'calme-scalp-gel',brand:'CALMÉ SCALP',name:'頭皮クレンジングジェル',category:'スカルプケア',concerns:['頭皮ケア'],size:'150 g',price:3190,stock:8,image:'products/calme-scalp-gel.webp',tag:'',summary:'シャンプー前に。毛穴の汚れを浮かせる頭皮用ジェル。',description:'シャンプー前に使う頭皮用のクレンジングをイメージしたデモ商品です。',sku:'CS-GL-015',dealerId:'botanica'},
 {id:'calme-scalp-mist',brand:'CALMÉ SCALP',name:'頭皮用 クールミスト',category:'スカルプケア',concerns:['頭皮ケア','ボリュームアップ'],size:'120 mL',price:2860,stock:21,image:'products/calme-scalp-mist.webp',tag:'',summary:'ひんやり爽快。汗ばむ季節の頭皮をすっきり。',description:'汗ばむ季節の頭皮をすっきり整えるミストをイメージしたデモ商品です。',sku:'CS-MS-012',dealerId:'botanica'},
 {id:'noir-wax-soft',brand:'NOIR ATELIER',name:'ソフト ヘアワックス',category:'ヘアスタイリング',concerns:['パーマケア'],size:'80 g',price:2200,stock:25,image:'products/noir-wax-soft.webp',tag:'',summary:'やわらかな束感。パーマのカールを生かす。',description:'やわらかな束感と、パーマのカールを生かす仕上げをイメージしたワックスのデモ商品です。',sku:'NA-WX-080S',dealerId:'sena'},
 {id:'noir-wax-hard',brand:'NOIR ATELIER',name:'ハード ヘアワックス',category:'ヘアスタイリング',concerns:[],size:'80 g',price:2200,stock:23,image:'products/noir-wax-hard.webp',tag:'',summary:'短い髪をしっかり立ち上げ、形をキープ。',description:'短めの髪をしっかり立ち上げる仕上げをイメージしたワックスのデモ商品です。',sku:'NA-WX-080H',dealerId:'sena'},
 {id:'noir-balm',brand:'NOIR ATELIER',name:'スタイリングバーム',category:'ヘアスタイリング',concerns:['ダメージヘア対策'],size:'40 g',price:2750,stock:14,image:'products/noir-balm.webp',tag:'NEW',summary:'髪にも手肌にも。自然なつやとまとまりを。',description:'髪にも手肌にも使えるバームをイメージしたデモ商品です。',sku:'NA-BM-040',dealerId:'sena'},
 {id:'noir-spray',brand:'NOIR ATELIER',name:'キープ スプレー',category:'ヘアスタイリング',concerns:[],size:'180 g',price:1980,stock:30,image:'products/noir-spray.webp',tag:'POPULAR',summary:'仕上げた形を一日キープ。べたつかない。',description:'仕上げた形を一日キープすることをテーマにしたスプレーのデモ商品です。',sku:'NA-SP-180',dealerId:'sena'},
 {id:'noir-styling-oil',brand:'NOIR ATELIER',name:'ウェット スタイリングオイル',category:'ヘアオイル',concerns:['パーマケア'],size:'100 mL',price:2640,stock:6,image:'products/noir-styling-oil.webp',tag:'',summary:'濡れたようなつやと、ほどよい束感を。',description:'濡れたようなつやと束感をつくるスタイリングオイルのデモ商品です。',sku:'NA-OL-100',dealerId:'botanica'},
 {id:'haru-shampoo',brand:'HARU ORGANICS',name:'オーガニック シャンプー',category:'シャンプー',concerns:['頭皮ケア','カラーケア'],size:'300 mL',price:2750,stock:18,image:'products/haru-shampoo.webp',tag:'',summary:'やさしい洗い心地と、植物の香り。',description:'やさしい洗い心地と、植物の香りをテーマにしたシャンプーのデモ商品です。',sku:'HO-SH-030',dealerId:'botanica'},
 {id:'haru-treatment',brand:'HARU ORGANICS',name:'オーガニック トリートメント',category:'トリートメント',concerns:['カラーケア'],size:'250 g',price:2750,stock:17,image:'products/haru-treatment.webp',tag:'',summary:'軽やかに仕上がる、オーガニックトリートメント。',description:'シャンプーと同じシリーズの、軽やかに仕上げるトリートメントのデモ商品です。',sku:'HO-TR-025',dealerId:'botanica'},
 {id:'haru-milk',brand:'HARU ORGANICS',name:'オーガニック ヘアミルク',category:'ヘアミルク・ミスト',concerns:['ダメージヘア対策'],size:'100 mL',price:2420,stock:0,image:'products/haru-milk.webp',tag:'',summary:'乾燥しがちな毛先を、やさしく整えるヘアミルク。',description:'毛先の乾燥をやさしく整えるヘアミルクのデモ商品です。入荷待ちの表示を確かめるため、初期在庫は0です。',sku:'HO-ML-010',dealerId:'botanica'},
 {id:'irodori-shampoo-purple',brand:'IRODORI COLOR',name:'カラーシャンプー パープル',category:'シャンプー',concerns:['カラーケア','白髪対策'],size:'250 mL',price:2530,stock:20,image:'products/irodori-shampoo-purple.webp',tag:'NEW',summary:'ブリーチ後の黄ばみを抑え、透明感のある髪色に。',description:'ブリーチ後の黄ばみを抑えることをテーマにした、紫のカラーシャンプーのデモ商品です。',sku:'IC-SH-025P',dealerId:'sena'},
 {id:'irodori-shampoo-pink',brand:'IRODORI COLOR',name:'カラーシャンプー ピンク',category:'シャンプー',concerns:['カラーケア'],size:'250 mL',price:2530,stock:12,image:'products/irodori-shampoo-pink.webp',tag:'',summary:'ピンク系のカラーを、長く楽しむために。',description:'ピンク系のヘアカラーを長く楽しむことをテーマにしたカラーシャンプーのデモ商品です。',sku:'IC-SH-025K',dealerId:'sena'},
 {id:'irodori-mask',brand:'IRODORI COLOR',name:'カラーキープ ヘアマスク',category:'ヘアマスク',concerns:['カラーケア','ダメージヘア対策'],size:'200 g',price:3190,stock:10,image:'products/irodori-mask.webp',tag:'',summary:'カラー後の髪色と手ざわりを、しっとり守る。',description:'カラー後の髪の色もちと手ざわりをテーマにしたヘアマスクのデモ商品です。',sku:'IC-MK-020',dealerId:'sena'},
 {id:'irodori-mist',brand:'IRODORI COLOR',name:'色もち ヘアミスト',category:'ヘアミルク・ミスト',concerns:['カラーケア'],size:'120 mL',price:2310,stock:24,image:'products/irodori-mist.webp',tag:'',summary:'紫外線やドライヤーの熱から、髪色を守るミスト。',description:'紫外線やドライヤーの熱から髪色を守ることをテーマにしたミストのデモ商品です。',sku:'IC-MS-012',dealerId:'sena'}
];
// 仕様書 2.2.8「お悩み別検索」の想定カテゴリ。商品の concerns はこの中から設定する。
export const concernCategories = ['ダメージヘア対策','エイジングケア','白髪対策','ボリュームアップ','頭皮ケア','カラーケア','パーマケア'];
